[package]
name = "pedigree"
version = "0.1.0"
authors = ["deadcheat <feat.dead.cheat+github@gmail.com>"]

[dependencies]
time = "0.1"
iron = "*"
fruently = "~0.8.0"
params = "0.6.0"
clap = "2.24.0"
lazy_static = "0.2"