// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/deadcheat/pedigree/logger (interfaces: Loggable)

package logger

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Loggable interface
type MockLoggable struct {
	ctrl     *gomock.Controller
	recorder *_MockLoggableRecorder
}

// Recorder for MockLoggable (not exported)
type _MockLoggableRecorder struct {
	mock *MockLoggable
}

func NewMockLoggable(ctrl *gomock.Controller) *MockLoggable {
	mock := &MockLoggable{ctrl: ctrl}
	mock.recorder = &_MockLoggableRecorder{mock}
	return mock
}

func (_m *MockLoggable) EXPECT() *_MockLoggableRecorder {
	return _m.recorder
}

func (_m *MockLoggable) Log(_param0 interface{}) error {
	ret := _m.ctrl.Call(_m, "Log", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockLoggableRecorder) Log(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Log", arg0)
}
